import { HardwareItem } from '../models/hardware-item.model';

/**
 * ============================================================================
 * MOCK DATASET: Hardware Items (Articles Matériels)
 * ============================================================================
 * Données exemple alignées sur les LCN du projet M88 (MOCK_S3000L_ENGINE).
 *
 * // TODO: [API BACKEND] Pour brancher votre vraie API :
 * // 1. GET /api/v1/projects/:projectId/hardware-items
 * // 2. POST /api/v1/projects/:projectId/hardware-items (création)
 * // 3. PUT /api/v1/projects/:projectId/hardware-items/:id (modification)
 * // 4. DELETE /api/v1/projects/:projectId/hardware-items/:id
 */
export const MOCK_HARDWARE_ITEMS: HardwareItem[] = [
  {
    id: 'hw-001',
    lcn: 'E01-01',
    name: 'Rotor de Compresseur HP',
    partNumber: 'PN-HP-ROT-409',
    nsnNumber: '2840-12-345-6789',
    cageCode: 'F0221',
    smrCode: 'PAOGD',
    qpa: 1,
    unitPrice: 285000,
    currency: 'EUR',
    replacementLevel: 'D',
    leadTimeDays: 180,
    weight: 42.5,
    isLru: false,
    isSru: true,
    description: 'Ensemble aubagé monobloc titane Ti-6Al-4V avec traitement de surface TBC. Révision en atelier agréé uniquement.',
    interchangeableWith: ['PN-HP-ROT-409A', 'PN-HP-ROT-408'],
    projectId: 'proj-m88-s3000l'
  },
  {
    id: 'hw-002',
    lcn: 'E01-01-01',
    name: 'Aubes de Compresseur HP — Étages 1 à 3',
    partNumber: 'PN-BLD-7812',
    nsnNumber: '2840-12-456-7890',
    cageCode: 'F0221',
    smrCode: 'PAOGH',
    qpa: 28,
    unitPrice: 4200,
    currency: 'EUR',
    replacementLevel: 'I',
    leadTimeDays: 60,
    weight: 0.38,
    isLru: false,
    isSru: true,
    description: "Aubes de compresseur en alliage titane haute pression. Contrôle boroscopique obligatoire à chaque visite 150 FH.",
    projectId: 'proj-m88-s3000l'
  },
  {
    id: 'hw-003',
    lcn: 'E01-01-02',
    name: 'Disque de Rotor Principal',
    partNumber: 'PN-DSC-9901',
    cageCode: 'F0221',
    smrCode: 'PAOGD',
    qpa: 1,
    unitPrice: 95000,
    currency: 'EUR',
    replacementLevel: 'D',
    leadTimeDays: 120,
    weight: 18.2,
    isLru: false,
    isSru: false,
    description: "Disque rotor principal en Inconel 718 forgé. Durée de vie limite : 12 000 FC. Non réparable en ligne.",
    projectId: 'proj-m88-s3000l'
  },
  {
    id: 'hw-004',
    lcn: 'E01-02-01',
    name: 'Vannes de Décharge — Bleed Valves',
    partNumber: 'PN-VLV-334',
    nsnNumber: '1650-12-567-8901',
    cageCode: 'F0055',
    smrCode: 'PAOGH',
    qpa: 4,
    unitPrice: 8500,
    currency: 'EUR',
    replacementLevel: 'O',
    leadTimeDays: 21,
    weight: 1.2,
    isLru: true,
    isSru: false,
    description: "Vanne de décharge pneumatique du compresseur HP. Remplacement en ligne par technicien B1.3. LRU.",
    projectId: 'proj-m88-s3000l'
  },
  {
    id: 'hw-005',
    lcn: 'E01-02-02',
    name: 'Directrices à Géométrie Variable — VSV',
    partNumber: 'PN-VSV-881',
    cageCode: 'F0221',
    smrCode: 'PAOGD',
    qpa: 1,
    unitPrice: 32000,
    currency: 'EUR',
    replacementLevel: 'I',
    leadTimeDays: 45,
    weight: 8.7,
    isLru: false,
    isSru: true,
    description: "Ensemble directrices variables du stator HP avec actuateurs. Réparable au niveau intermédiaire agréé.",
    projectId: 'proj-m88-s3000l'
  },
  {
    id: 'hw-006',
    lcn: 'E02-01-01',
    name: 'Gicleur Haute Pression Carburant',
    partNumber: 'PN-NOZ-011',
    nsnNumber: '2840-12-678-9012',
    cageCode: 'F0055',
    smrCode: 'PAOGH',
    qpa: 18,
    unitPrice: 1850,
    currency: 'EUR',
    replacementLevel: 'O/I',
    leadTimeDays: 14,
    weight: 0.12,
    isLru: true,
    isSru: false,
    description: "Injecteur de carburant HP avec filtre intégré. Contrôle de débit à 300 FH. Échangeable standard en ligne.",
    projectId: 'proj-m88-s3000l'
  },
  {
    id: 'hw-007',
    lcn: 'E02-02-01',
    name: 'Aubes de Turbine Monocristallines HP',
    partNumber: 'PN-BLD-MONO-09',
    cageCode: 'F0221',
    smrCode: 'PAOGD',
    qpa: 24,
    unitPrice: 22500,
    currency: 'EUR',
    replacementLevel: 'D',
    leadTimeDays: 240,
    weight: 0.65,
    isLru: false,
    isSru: false,
    description: "Aubes monocristallines en AM1 avec barrière thermique EB-PVD. Durée de vie: 8 000 FH. Réparation dépôt industriel uniquement.",
    projectId: 'proj-m88-s3000l'
  },
  {
    id: 'hw-008',
    lcn: 'E03-01',
    name: 'Unité de Contrôle Numérique FADEC (ECU)',
    partNumber: 'PN-ECU-9900X',
    nsnNumber: '5895-12-789-0123',
    cageCode: 'F0987',
    smrCode: 'PAOGH',
    qpa: 2,
    unitPrice: 148000,
    currency: 'EUR',
    replacementLevel: 'O',
    leadTimeDays: 30,
    weight: 3.8,
    isLru: true,
    isSru: false,
    description: "Calculateur FADEC redondant A/B. LRU échangeable en ligne par B2 avionique. Chargement logiciel certifié.",
    interchangeableWith: ['PN-ECU-9900Y'],
    projectId: 'proj-m88-s3000l'
  },
  {
    id: 'hw-009',
    lcn: 'E03-01-02',
    name: 'Module Capteurs de Pression P3/T3',
    partNumber: 'PN-SNS-P3',
    cageCode: 'F0987',
    smrCode: 'PAOGH',
    qpa: 3,
    unitPrice: 6800,
    currency: 'EUR',
    replacementLevel: 'O',
    leadTimeDays: 10,
    weight: 0.45,
    isLru: true,
    isSru: false,
    description: "Capteur combiné pression/température HP compresseur. Étalonnage FADEC requis après remplacement.",
    projectId: 'proj-m88-s3000l'
  },
];
